fail CI if tests fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,8 +20,8 @@ jobs:
         os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install project
@@ -38,53 +38,15 @@ jobs:
         os: [ubuntu-latest]
     runs-on: ${{ matrix.os }}
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v2
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install project
         run: make install
       - name: Run tests
-        run: make test
+        run: make test || exit 1  # Exit with error code if tests fail
       - name: "Upload coverage to Codecov"
         uses: codecov/codecov-action@v3
         with:
-          fail_ci_if_error: true
-
-  # tests_mac:
-  #   needs: linter
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       python-version: [3.9]
-  #       os: [macos-latest]
-  #   runs-on: ${{ matrix.os }}
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - uses: actions/setup-python@v2
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
-  #     - name: Install project
-  #       run: make install
-  #     - name: Run tests
-  #       run: make test
-
-  # tests_win:
-  #   needs: linter
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       python-version: [3.9]
-  #       os: [windows-latest]
-  #   runs-on: ${{ matrix.os }}
-  #   steps:
-  #     - uses: actions/checkout@v2
-  #     - uses: actions/setup-python@v2
-  #       with:
-  #         python-version: ${{ matrix.python-version }}
-  #     - name: Install Pip
-  #       run: pip install --user --upgrade pip
-  #     - name: Install project
-  #       run: pip install -e .[test]
-  #     - name: run tests
-  #       run: pytest -s -vvvv -l --tb=long tests
+          fail_ci_if_error: false
